noble-assets/noble

app/app.go

`SetInitChainer` and `SetBeginBlocker` were both being called twice, this PR removes the redundant calls.

Remove redundant calls to SetInitChainer and SetBeginBlocker

---

x/tokenfactory/blockibc_middleware.go

If the tokenfactory is in a paused state we want to explicitly reject incoming ics20 transfers for the minting denom

Dont process incoming ics20 transfers for minting denom if tokenfactory is paused

---

x/tokenfactory/blockibc_middleware.go

Previously we were checking the incoming packets full denom against the minting denom so the check was always true due to the way denoms are composed in ics20 e.g. `transfer/channel-40/drachma`

Check incoming transfers base denom against the minting denom

---

x/tokenfactory/types/genesis.go
x/tokenfactory/types/genesis_test.go

Previously we were passing the `MinterController.Minter` address in the genesis state validation but we should be using the `MinterController.Controller` address

Pass correct minter controller address in genesis state validation

---

Makefile
x/tokenfactory/types/message_burn.go
x/tokenfactory/types/message_burn_test.go
x/tokenfactory/types/message_configure_minter.go
x/tokenfactory/types/message_configure_minter_test.go
x/tokenfactory/types/message_mint.go
x/tokenfactory/types/message_mint_test.go

Previously we were not validating the amounts or allowances in `MsgMint` `MsgBurn` or `MsgConfigureMinter` to be non-nil and greater than zero

Validate burn/mint amounts and minter allowances are greater than zero

---

x/tokenfactory/client/cli/tx_blacklist.go
x/tokenfactory/client/cli/tx_burn.go
x/tokenfactory/client/cli/tx_configure_minter.go
x/tokenfactory/client/cli/tx_configure_minter_controller.go
x/tokenfactory/client/cli/tx_mint.go
x/tokenfactory/client/cli/tx_pause.go
x/tokenfactory/client/cli/tx_remove_minter.go
x/tokenfactory/client/cli/tx_remove_minter_controller.go
x/tokenfactory/client/cli/tx_unblacklist.go
x/tokenfactory/client/cli/tx_unpause.go
x/tokenfactory/client/cli/tx_update_blacklister.go
x/tokenfactory/client/cli/tx_update_master_minter.go
x/tokenfactory/client/cli/tx_update_owner.go
x/tokenfactory/client/cli/tx_update_pauser.go

`ValidateBasic` already gets called in `GenerateOrBroadcastTxCLI` so there is no reason to explicitly call it in each of the tx cli call sites

Remove duplicated calls to ValidateBasic

---

x/tokenfactory/keeper/keeper.go
x/tokenfactory/keeper/msg_server_update_blacklister.go
x/tokenfactory/keeper/msg_server_update_master_minter.go
x/tokenfactory/keeper/msg_server_update_owner.go
x/tokenfactory/keeper/msg_server_update_pauser.go
x/tokenfactory/types/errors.go
x/tokenfactory/types/genesis.go
x/tokenfactory/types/genesis_test.go

This PR introduces privileged role separation by ensuring that an address cannot be assigned to more than one privileged role i.e. `Owner` `Blacklister` `Pauser` & `MasterMinter` must be different addresses. We ensure this is enforced by checking if an address has already been delegated to some role at genesis as well as during any attempts to update a role.

Enforce privileged role separation

---

readme.md

This PR updates the Access Control Table on the readme. 
After #127, it is possible to transfer a non-tokenfactory asset while the chain is paused.

Update Access Control Table

---

app/upgrades/radon/upgrade.go
interchaintest/upgrade_test.go

In the `globalfee` parameters,
this patch changes the fee from `0.01udrachma` to `0uusdc`
It also adds extra messages to `BypassMinFeeMsgTypes`.

`denom_metadata` patch for `radon` upgrade

---

app/upgrades/radon/upgrade.go
interchaintest/upgrade_test.go

Ultimately, this PR cherry-picks: #160
It sets the minimum gas fee in the `globalfee` params to be `0uusdc`
It also adds extra message types to BypassMinFeeMsgTypes.

Update `radon` upgrade handler (Cherry-pick: #160)

---

x/tariff/keeper/allocation.go

Because of the way fees to the distribution entities were getting truncated, it was possible for the tariff module to try and distribute a zero-amount fee which would cause a consensus failure. 
Specifically if the IBC transaction was between 10,000 - 19,999.

Handle Zero Amount Coins to Entities

---

x/tariff/keeper/allocation.go

This avoids a chain halt in the rare case there is an error distributing fees to the distribution entities.

Log error instead of panic during BeginBlocker token allocations

---

x/tariff/types/params.go

This PR add extra checks that:
- does not allow distribution entities to have a zero share amount. 
- does not allow there to be multiple distribution entities with the same address

Check for zero shares and dupe addresses

---

go.mod
go.sum

This will allow the packet forward middleware timeout key to work with duration strings ("10m"). It previously only accepted uint64 values.

Update Packet Forward Middleware

---

x/tariff/keeper/allocation.go

In the Tariff module, if there are zero fees to distribute, there is no need to loop through all the distribution entities to divide out a zero amount.

Make more efficient if zero fees to distribute

---

Makefile

This change allows noble to report the proper version when running nobled version.  I believe the issue was git describe --exact-match returns...
fatal: no tag exactly matches '55d62161961a10e0c5c3174b42676ca3d3be1eae'

version fix

---

.github/workflows/e2e-tests.yaml
Makefile
app/app.go
cmd/root.go
go.mod
go.sum
interchaintest/go.mod
interchaintest/go.sum
interchaintest/ibc_client_expire_substitute_test.go
interchaintest/ibc_client_unfreeze_test.go

Add capability for IBC proposals (client substitution and ibc upgrade) to be executed by the upgrade authority.
2 new msgs (`MsgClientUpdate`, `MsgUpgrade`), msg handlers, and CLI commands.
`MsgClientUpdate` allows the upgrade authority to substitute a new light client state into an existing one, allowing recovery of expired clients.

ibc client authority

---

app/app.go
cmd/root.go
go.mod
go.sum
interchaintest/go.mod
interchaintest/go.sum
interchaintest/ibc_substitute_expired_client_test.go

The CLI client substitution command was not working due to an unregistered codec. Fix in paramauthority: https://github.com/strangelove-ventures/paramauthority/pull/16

Add AppModuleBasic for ibc authority

---

.changelog/unreleased/dependencies/250-bump-pfm.md
go.mod
go.sum

Bump the Packet Forward Middleware from `v4.1.0` to `v4.1.1` to patch ViperStrike vulnerability.

chore: bump pfm to `v4.1.1`

---

interchaintest/cctp_deposit_for_burn_test.go
interchaintest/cctp_deposit_for_burn_with_caller_test.go
interchaintest/cctp_receive_message_test.go
interchaintest/cctp_receive_message_with_caller_test.go
interchaintest/cctp_replace_deposit_for_burn_test.go
interchaintest/genesis_test.go
interchaintest/ibc_bps_fee_test.go
interchaintest/noble_test.go
interchaintest/upgrade_argon_test.go
interchaintest/upgrade_grand-1_test.go
interchaintest/upgrade_noble-1_test.go

This PR...
1) Changes the denoms used for the tests to match mainnet denoms (uusdc and frienzies)
2) Uses better named and more clear mock images `"mock-v0.4.2"`, `"mock-v2.0.0"` in the upgrade tests.
3) Adds back the argon post upgrade tests

Mock tests for v4.0.0

---

.github/workflows/docker-publish.yaml
.github/workflows/draft-release.yaml
.github/workflows/e2e-tests.yaml
.github/workflows/simulation-tests.yaml
.github/workflows/unit-tests.yaml
go.mod
go.sum
interchaintest/go.mod
interchaintest/go.sum

This PR temporarily replaces the CCTP dependency so that we can continue development while Circle open sources the codebase. It is planned to revert these changes once the repository is open sourced!

chore: temporarily replace cctp dependency

---

.changelog/unreleased/dependencies/385-cosmos-sdk.md
go.mod
go.sum

Now that [Halborn](https://www.halborn.com) has completed their audit of our Cosmos SDK fork, we have cut a tag to be included in the v5 release.

chore: switch to tagged cosmos sdk fork

---

e2e/fiat_tf_test.go
e2e/utils.go

Includes:
- `TestFiatTFUpdateOwner`
- `TestFiatTFAcceptOwner`

feat: owner e2e tests for fiattokenfactory

---

e2e/fiat_tf_test.go
e2e/utils.go

Includes:
- `TestFiatTFUpdateMasterMinter`
- `TestFiatTFConfigureMinterController`
- `TestFiatTFRemoveMinterController`
- `TestFiatTFConfigureMinter`
- `TestFiatTFRemoveMinter`

feat: minter e2e tests for fiattokenfactory

---

e2e/fiat_tf_test.go
e2e/utils.go

Includes:
- `TestFiatTFUpdatePauser`
- `TestFiatTFPause`
- `TestFiatTFUnpause`

feat: pause e2e tests for fiattokenfactory

---

e2e/fiat_tf_test.go
e2e/utils.go

Includes:
- `TestFiatTFUpdateBlacklister`
- `TestFiatTFBlacklist`
- `TestFiatTFUnblacklist`

feat: blacklist e2e tests for fiattokenfactory

---

e2e/fiat_tf_test.go

Includes:
- `TestFiatTFMint`
- `TestFiatTFBurn`

feat: mint & burn e2e tests for fiattokenfactory

---

e2e/fiat_tf_test.go

Includes:
- `TestFiatTFAuth`
- `TestFiatTFAuthzGrant`
- `TestFiatTFAuthzSend`
- `TestFiatTFBankSend`

feat: auth, authz, bank e2e tests for fiattokenfactory

---

e2e/conformance_test.go
e2e/module_check_test.go

This CI test ensures that certain Go modules are not included in Noble.

chore: add restricted module check

---

app.go

As discovered in #422, the initial module version map passed to the `x/upgrade` Keeper was missing legacy modules.
This PR addresses this by reseting the initial version map once all modules (including legacy) have been registered!

fix: correctly initialize module version map

---

.changelog/unreleased/dependencies/431-bump-halo.md
e2e/go.mod
e2e/go.sum
go.mod
go.sum

This PR bumps the Halo module responsible for issuing Hashnote's USYC to the latest patch release.
[🗒️  `v2.0.1` Release Notes 🗒️](https://github.com/noble-assets/halo/releases/tag/v2.0.1)

chore: bump halo to `v2.0.1`

---

cmd/root.go
local.sh

This PR overwrites the cometbft default `timeout_commit` from `5s` to `500ms`. 
You will be able to see this change take effect when initializing Noble (`nobled init`).
For context, `500ms` is what the current Noble validator set has manually adjusted in the `config.toml` file.

chore: overwrite default cometbft `timeout_commit`

---

.changelog/unreleased/dependencies/481-bump-forwarding.md
.changelog/unreleased/dependencies/481-some-new-feature.md
ante.go
app.go
go.mod
go.sum

- Bump the Forwarding module to version 2.0.1
- Wire the forwarding module ante handler to allow signerlessly registration of forwarding accounts.

chore: bump forwarding module and wire ante

---

local_net/in-place-fork.sh

Removed genesis file download  from the `in-place-fork.sh` script.
I have just now realized that pulling the genesis file is not needed when state syncing a node.

chore: optimize `in-place-fork` script

---

go.mod
go.sum

This PR switches the Packet Forward Middleware dependency to our fork, in order to cleanup logging when migrating from consensus version 2 to 3. This needs to wait for https://github.com/noble-assets/ibc-apps/pull/1 to be merged and tagged!

chore: bump pfm to improve logging

---

.changelog/unreleased/bug-fixes/515-empty-injections.md
.changelog/unreleased/bug-fixes/515-fix-tx-injections.md
proposal.go

This PR addresses an issue where empty `sdk.Msg`'s were unnecessarily injected into block proposals.
This occurs when the proposing validator’s instance of Jester has VAAs queued up, but a previous validator has already injected those VAAs in a prior block.
This is consensus breaking.

fix: ensure non-empty tx injections

---

app.go
upgrade/upgrade.go

This PR adds logic to the v10 upgrade handler that claims the $USDN yield accrued by the Noble Swap pools.
This has been tested against a mainnet mirror network at block 24931000:

feat: claim swap pools yield in upgrade handler

---

api/gen/swagger.yaml
api/generate.sh

Through multiple PRs, we bumped the version of the Hyperlane dependency to `v1.0.0`, but never updated the Swagger file.

chore: regenerate swagger for hyperlane

---

go.mod
upgrade/constants.go

The `v10.0.0-beta.0` upgrade was registered incorrectly on chain as `stratrum` and not `stratum`. This PR updates the name to correctly upgrade testnet.

fix: use registered upgrade name

---

go.mod
upgrade/constants.go

This reverts commit #542, as we will use the correct upgrade name for mainnet.

chore: revert upgrade name change

---

.github/workflows/docker-publish.yaml
.github/workflows/draft-release.yaml
.github/workflows/e2e-tests.yaml

This is a temporary solution to the issues we've been running into with Heighliner in GitHub Actions ever since [musl.cc](https://musl.cc) blocked GitHub Action runners. The long term solution to this is removing Heighliner entirely which is WIP in #557 😄

fix: bump heighliner fork with musl proxy

---

app.go
e2e/upgrade_test.go
e2e/utils.go
upgrade/constants.go
upgrade/store.go
upgrade/upgrade.go

Now that the `v10.0.0-rc.0` upgrade has been successfully executed on Noble's Testnet, we can re-add the v10 Stratum upgrade handler with any additional changes in preparation for the upgrade on Noble's Mainnet!

chore: re-add stratum upgrade handler

---

.changelog/unreleased/improvements/597-shido-client.md
app.go
e2e/upgrade_test.go
e2e/utils.go
upgrade/upgrade.go

This PR adds upgrade logic to the v11 Flux line to recover the expired [Shido](https://shido.io/) IBC light client.
This has been tested locally against an in-place fork of mainnet :

chore: recover expired shido ibc light client
